package se.yrgo.dataaccess;

import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;


public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String UPDATE_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?, ?, ?, ?, ?)";
    private static final String DELETE_SQL = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";

    private static final String GET_BY_ID_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String GET_BY_NAME_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMER WHERE COMPANY_NAME LIKE ?";
    private static final String GET_ALL_SQL = "SELECT CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES FROM CUSTOMER";
    private static final String INSERT_CALL_SQL = "INSERT INTO CUSTOMER_CALL (CUSTOMER_ID, TIME_AND_DATE, NOTES) VALUES (?,?,?)";
    private static final String GET_CALLS_FOR_CUSTOMER_SQL = "SELECT ID, TIME_AND_DATE, NOTES FROM CUSTOMER_CALL WHERE CUSTOMER_ID=?";

    private JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        this.createTables();
    }

    private void createTables() {
        try {
            this.template.update("""
                        CREATE TABLE CUSTOMER (
                            CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
                            COMPANY_NAME VARCHAR(100),
                            EMAIL VARCHAR(100),
                            TELEPHONE VARCHAR(30),
                            NOTES VARCHAR(255)
                        )
                    """);
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Assuming the CUSTOMER table already exists");
        }


        try {
            this.template.update("""
                   CREATE TABLE CUSTOMER_CALL (
                        ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
                        CUSTOMER_ID VARCHAR(20),
                        TIME_AND_DATE TIMESTAMP,
                        NOTES VARCHAR(255),
                        PRIMARY KEY (ID),
                        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
                    )""");
        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println(" Assuming the CUSTOMER_CALL table already exists");
        }
    }


    @Override
    public void create(Customer customer) {
        template.update(INSERT_SQL,
                customer.getCustomerId(),
                customer.getCompanyName(),
                customer.getEmail(),
                customer.getTelephone(),
                customer.getNotes());
    }


    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        try {
            return template.queryForObject(GET_BY_ID_SQL, new CustomerRowMapper(), customerId);
        } catch (EmptyResultDataAccessException e) {
            throw new RecordNotFoundException();
        }
    }


    @Override
    public List<Customer> getByName(String name) {
        return this.template.query(GET_BY_NAME_SQL, new CustomerRowMapper(), "%" + name + "%");
    }


    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        int rowsUpdated = this.template.update(UPDATE_SQL,
                customerToUpdate.getCompanyName(),
                customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(),
                customerToUpdate.getNotes(),
                customerToUpdate.getCustomerId());

        if (rowsUpdated == 0) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        int rowsDeleted = this.template.update(DELETE_SQL, oldCustomer.getCustomerId());

        if (rowsDeleted == 0) {
            throw new RecordNotFoundException();
        }
    }

    @Override
    public List<Customer> getAllCustomers() {
        return this.template.query(GET_ALL_SQL, new CustomerRowMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer foundCustomer = this.getById(customerId);
        List<Call> calls = this.template.query(GET_CALLS_FOR_CUSTOMER_SQL, new CallRowMapper(), customerId);
        foundCustomer.setCalls(calls);
        return foundCustomer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        this.getById(customerId);

        this.template.update(INSERT_CALL_SQL,
                customerId,
                new Timestamp(newCall.getTimeAndDate().getTime()),
                newCall.getNotes());
    }


    class CustomerRowMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int arg1) throws SQLException {
            String customerId = rs.getString(1);
            String companyName = rs.getString(2);
            String email = rs.getString(3);
            String telephone = rs.getString(4);
            String notes = rs.getString(5);

            return new Customer(customerId, companyName, email, telephone, notes);
        }
    }

    class CallRowMapper implements RowMapper<Call> {
        @Override
        public Call mapRow(ResultSet rs, int arg1) throws SQLException {
            Timestamp timeAndDate = rs.getTimestamp(2);
            String notes = rs.getString(3);

            return new Call(notes, timeAndDate);
        }
    }
}